# 通常有効だけど無効にするルール
disabled_rules:
- trailing_whitespace # Xocdeの自動生成ファイルで警告が出るため
- vertical_whitespace # Xocdeの自動生成ファイルで警告が出るため
- trailing_newline # Xocdeの自動生成ファイルで警告が出るため
- nesting # クロージャの使用ですぐに警告が出るため
- trailing_closure # 括弧と一緒にクロージャ使う時とか省略できない場面があるから
- todo # すぐに修正できない場合があり、pushの度にlintに引っかかってbotに書き込まれるのがノイズになるから
- type_contents_order
- type_name
- file_types_order
- identifier_name # 2文字を許容したいから
- switch_case_alignment
- force_unwrapping
- force_cast
- force_try
- cyclomatic_complexity

# 通常無効だけど有効にするルール
opt_in_rules:
- empty_string
- empty_count
- empty_collection_literal
- trailing_closure
- unowned_variable_capture
- unused_import
- first_where
- last_where
- contains_over_first_not_nil
- type_contents_order

line_length:
- 200   # warning

function_body_length:
- 100   # warning

# 変数名が2文字以上なら許可
identifier_name:
  min_length:
    error: 1
  excluded: # 以下の単語は定形語のためルールの対象外とする。
    - id
    - db
    - URL
    - x
    - y
    - vc
    - on

# SwiftLintの適用から外すディレクトリ
excluded:
- Carthage/
- Cartfile
- Cartfile.resolved
- R.generated.swift
- Pods
- SourcePackages
