name: Danger Swift

on: [push, pull_request]

jobs:
  danger:
    name: Danger
    runs-on: macos-11
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
            ruby-version: '2.7'
      - name: cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: setup bundle
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run Danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bundle exec danger

  tests:
    name: Tests
    runs-on: macos-11
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.0.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
            ruby-version: '2.7'
      - name: cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: setup bundle
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Cache Swift Packages
        uses: actions/cache@v1
        with:
          path: SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('*.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-spm-
      - name: Test
        run: |
          bundle exec fastlane scan
