name: Test Swift

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-10.15
    timeout-minutes: 15
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
            ruby-version: '2.x'
      - name: cache bundle
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: setup bundle
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          - name: Setup - Xcode
      - name: Setup - Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.5.app
      - name: Test - Fastlane tests
        run: bundle exec fastlane scan
