name: Test Swift

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: swift build -v
        xcodebuild test -project RockMap.xcodeproj -scheme RockMap -destination 'platform=iOS Simulator, name=iPhone 12, OS=13.6'
      - name: Run tests
        run: swift test
