name: Test Swift

on: [push]

jobs:
  test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Show Xcode list
        run: ls /Applications | grep 'Xcode'
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Xcode build
        run: set -o pipefail &&
          xcodebuild
          -sdk iphonesimulator
          -configuration Debug
          -project RockMap.xcodeproj
          -scheme RockMap
          build
      - name: Xcode test
        run: set -o pipefail &&
          xcodebuild
          -sdk iphonesimulator
          -configuration Debug
          -project RockMap.xcodeproj
          -scheme RockMap
          -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5'
          clean test
